 {% set name = "tosholi" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tosholi-{{ version }}.tar.gz
  sha256: 326ca4b8d8310b32af99e8be73a3b6628b30f3c8b4dbb8e7bc60e42a25a91a52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - dacite
    - tomli
    - tomli-w

test:
  imports:
    - tosholi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gpauloski/tosholi
  summary: Read and write TOML config files with dataclasses.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
